#!/usr/bin/env node
var fs = require('fs');
var child_process = require('child_process');

child_process.exec('yarn start:signal', (err, stdout, stderr) => {
  if (err) {
    // node couldn't execute the command
    fs.appendFile('/var/www/robot/web/reports/server/signal-error.txt', err, function (err) {
      // if (err) throw err;
    })
    return;
  } else {
    fs.appendFile('/var/www/robot/web/reports/server/signal-error.txt', stderr, function (err) {
      // if (err) throw err;
    })
  }

  fs.appendFile('/var/www/robot/web/reports/server/signal.txt', stdout, function (err) {
    // if (err) throw err;
  })
});